services:
  ultraviolet:
    image: webproxy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webproxy-ultraviolet
    restart: unless-stopped
    environment:
      - SOCKS_HOST=1.1.1.1
      - SOCKS_PORT=1080
    ports:
      - "30080:8080"
